### ISSUE TITLE
Nur ein Test?

### ISSUE THREAD

**Issue by mmtnrw** [hkiam/pool-heat-pump#1]
Also ich hab den Code hoch und runter kontrolliert, aber die Zeiten können nicht stimmen.

Weder mit dem Code compiliert auf nem ESP8266 noch auch einem ESP32 kommt da irgendwas bei raus.

Hast du vielleicht genauere Protokolldaten?

Ich habs komplett auf ESP Home umgesetzt, die Interrupts lösen entsprechend auch aus, aber er liest keine Kommandos. die Mehrteilige Prüfung der Pulse schlägt fehl, wenn ich da allerdings logge habe ich das Problem das die Zeiten überhaupt nicht stimmen.

**Comment by hkiam** [comment]
Nein es ist kein Test, ich habe es seit letztem Jahr im Betrieb und nutze es mit Node Red. 
Das Protokoll incl. LA Aufzeichnung liegt im Ordner „investigation“. Ist es die gleiche WP?

**Comment by mmtnrw** [comment]
Ich hab jetzt nen c3 und nen wemos d1.

beim wemos d1 fängt es schon damit an das der den mqtt nicht connected :( mehr als 100 Geräte gehen aber. Und der Wemos macht ein Timeout. <- selbiges beim c3 bei deinem Sketch.

Ich hab jetzt pin d7 genommen wie du vorgegeben hast beim d1 aber soweit komme ich dann ja nicht bei deinem sketch weil der pubsub nicht connected und mosquitto meldet timeout

d7 wäre ja mosi und du hast d6 (miso) auf high gesetzt, hat das nen hintergrund?

ich habs übersetzt auf den C3 und esphome und hab mal die durations geguckt, ich bekomme einen 8100 und einen 6stelligen im wechsel (das könnte natürlich auch sein das durch dass messaging in der log die zeit hoch geht), als wenn da ne anmeldung fehlt und der auf nen ping wartet. meine wärmepumpe ist ne hydropro, das display und der stecker sind auch identisch.

ich hab als levelshifter nen 2n7000 mit 2 10k widerständen zu 5 und 3,3 volt und die ein und ausgangsspannungen stimmen auch 5v hinterm 2n7000 und 3,3 zum esp

**Comment by hkiam** [comment]
Zum MQTT musst Du mal schauen, ob er die Konfiguration richtig ließt, die muss entweder als Default kompiliert oder im SPIFFS liegen.  Hierzu einfach mal ein paar Ausgabe einbauen und über die serielle Konsole schreiben. WIFI ist aber korrekt verbunden? 
Ich nutze auch Mosquito aber ohne Nutzer und Kennwort, ggf. kannst Du auch hier nochmal ansetzen.
Bezüglich PIN sollte es eigentlich egal sein, D7 war einfach meine Wahl. Die Umsetzung nutzt für den Empfang einen externen Interrupt auf dem Pin, solange das gegeben ist, passt es.  Das Protokoll ist proprietär und kein SPI oder ähnliches, MOSI, MISO spielen hierfür also keine Rolle. 
Das initialisieren von D6 war, soweit ich mich erinnere, mal für was anderes gedacht, spielt also auch keine Rolle.
Zum Levelshifter kann das so funktionieren, ich habe einfach einen fertigen aus der Kramkiste genommen. Wichtig ist, dass er Bidirektional funktioniert und auf 5V Pegel geht. Mit 3.3V funktioniert die WP nicht. Am besten wäre mal mit einem Oszi ein paar Frames aufzuzeichen. Alternativ/Zusätzlich gibt es auch billige Logic Analyzer, mit den man das Protokoll gut debuggen kann.
Hier habe ich mit einen kleinen Decoder. geschrieben um mit Salea die Kommunikation zwischen Display und Board zu entschlüsseln:
https://github.com/hkiam/pool-heat-pump/tree/main/investigation/Salea%20Decoder/Pool%20Heat%20Pump

Die Aufschlüsselung des Protokolls findest Du hier:
https://github.com/hkiam/pool-heat-pump/blob/main/investigation/protocol.md

Ein Anmeldung gibt es hier nicht, es ist im Prinzip ein sehr einfaches Protokoll. Dein 8100 bekomme ich hier nicht einsortiert, Fehler im Empfang? Dann müsste aber eigentlich einen Checksummenfehler kommen. Was wird den auf der seriellen Konsole ausgegeben?

**Comment by mmtnrw** [comment]
Hab mal geguckt was das Display denn an sich macht.

Im Endeffekt hat es einen PC817 optokoppler dessen kathode auf data gesetzt wird. und anode bekommt vom 6ten pin vom pic unten rechts den strom. dann wird vom pic unten links gegen ground emitted. und der j3 transistor ist für das senden der daten.

Mich wundert nur die Spannung 0 -> 2,5 -> 3,3 -> 4,2 und 5

der BSS138 deines Levelshifters reagiert etwas schneller als der 2N7000 da dieser auch 30pf Kapazität hat. Und die Schaltspannung auf Drain geringer ist.

Hab ich richtig vermutet?

Nur wenn ich wirklich 0 habe kommt ein Signal und wenn ich 2,5 und 3 habe bleibt bei mir High.
Saleae kommt morgen (du vergisst immer ein E bei SalEae). Saleae kommt leider erst morgen, aber das wollte ich auch nochmal Testen. Ich denke der Haken ist die schwankende Eingangsspannung vom Datapin der meinen PIN auf High stehen lässt. Oder sagen wir nahezu stehen lässt.

**Comment by mmtnrw** [comment]
So da bin ich wieder, tatsächlich haben wir ein fast identisches protokoll, aber ich hab 0,5 grad schritte in der Temperatur.
Ich hab 0x20 für off und 0x40 für cool und 0x60 für heat weiter habe ich nicht probiert.

deine todos etc habe ich habe erledigt. ich prüfe jetzt die länge von einem frame in microseconds und auch die länge der silence etc. und sende jetzt innerhalb der pause. das funktioniert tatsächlich sehr sehr gut. ich müsste es jetzt noch ein wenig schöner machen, aber wird jetzt wohl auch ein Jahr laufen. und ich erkenne auch die frame länge anhand der silence. somit ist es egal ob 10 oder 13 byte. ich hab 13 byte du 10. aber saleae und dein script hat es dann geregelt....


Ich poste dir das dann die tage..
